# Generated by Django 3.1.3 on 2020-12-01 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_mangement', '0004_auto_20201201_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='img',
            new_name='image',
        ),
    ]
