# Generated by Django 3.1.3 on 2020-12-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0002_auto_20201201_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='imgUrl',
        ),
        migrations.AddField(
            model_name='ad',
            name='img',
            field=models.ImageField(default='default.png', upload_to='ads_pics'),
        ),
    ]
