# Generated by Django 2.2 on 2020-12-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0005_auto_20201201_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='views',
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(upload_to='ads_pics'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='link',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
