# Generated by Django 3.1.4 on 2020-12-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0009_ad_approve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view',
            old_name='click_time',
            new_name='view_time',
        ),
    ]
