# Generated by Django 3.1.4 on 2020-12-07 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0010_auto_20201205_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='ad_id',
        ),
        migrations.RemoveField(
            model_name='click',
            name='advertiser_id',
        ),
        migrations.RemoveField(
            model_name='view',
            name='ad_id',
        ),
        migrations.RemoveField(
            model_name='view',
            name='advertiser_id',
        ),
        migrations.AddField(
            model_name='click',
            name='ad',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.ad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='view',
            name='ad',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.ad'),
            preserve_default=False,
        ),
    ]
