# Generated by Django 3.1.4 on 2020-12-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0011_auto_20201207_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='advertiser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.advertiser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='view',
            name='advertiser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='advertiser_management.advertiser'),
            preserve_default=False,
        ),
    ]
